version: 2
jobs:
  build:
    docker:
      - image: danteev/texlive
    steps:
      - checkout
      # normal compilation and release to homepage
      - run: latexmk main-german.tex
      - run: mkdir build && cp -r main-*.pdf .github/_config.yml docs/* build/
      - store_artifacts:
          path: build/
      - run: if [ "$CIRCLE_BRANCH" == "master" ]; then .circleci/deploy-ghpages.sh build/; fi
      # test pdflatex compilation
      - run: git clean -xdf
      - run: pdflatex main-german.tex
